#!/bin/bash 
# [GitAction] Xray Automated Subscribtion Sript

shopt -s expand_aliases 
# enabling expand_aliases 

source /root/.bashrc 
# source .bashrc 

echo -e "$(TZ='Asia/Shanghai' date)\n" 
# 时间戳 

# 生成的订阅文件放在网站根目录下 
# filePath='~/www/xray' 保留单引号在Ubuntu下导致no such file or directory的错误提示，不知何故。。。 
filePath=/github/xray 
rm -f cache pool 

# 下面的是我的xray节点信息 
lst="vless://45c72176-cffa-4366-96c9-54ef4ad68297@www.suzishan.com:443?type=tcp&encryption=none&security=xtls&path=%2f&headerType=none&flow=xtls-rprx-direct#" 

# generate a pool for port No.s (totally 10,001 prots No.) 
for (( i=0;i<=10000;i++ )) do echo $((i + 40000)); done | xargs shuf -n101 -e | sort >> pool 

# loop to replicate 
for i in {0..100} 
do 
    # 随机生成40000~50000之间的一个随机数 
    randPort=$(head -$((i+1)) pool | tail -1) 
    echo -e "Current Port("$(printf "%02d" $i)"): "$randPort 
    echo $lst$(printf "%02d" $i) | sed "s/443/$randPort/g" >> cache 
    # 重要：echo后面加-n会去除末尾的换行符. 而此处不加, 使得每行单独显示 
done 

cache=${cache::-1} 
#去除末尾的换行符 

echo -n "$(cat cache)" | base64 -w 0 > $filePath 
# 将更换端口后的节点信息base64写入文件 

echo -e "\nPorts updated.\n" 
push2github 
echo -e "\nUpdated subscribtion pushed to GitHub.\n" 
echo -e "$(TZ='Asia/Shanghai' date)" 
echo -e "\n" "--------------------------------" "\n"